Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pau-demo54321-bucket6789

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0866a3c8686eaeeba
      SubnetId: subnet-03d8f6c93e9bca852  # Replace <subnet-id> with your specific Subnet ID
      SecurityGroupIds:      # Specify the security group IDs as a list
        - sg-056d8552aeb782afa      